# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=0)),
                ('name', models.CharField(default=b'', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=10240)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('sub_title', models.CharField(blank=True, default=b'', max_length=1024)),
                ('max_vote', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1024)),
                ('content', models.CharField(max_length=10240)),
                ('count_vote', models.IntegerField(default=0)),
                ('count_visit', models.IntegerField(default=0)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=1)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Option')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Voter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
