# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20171219_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='viisted',
            new_name='visted',
        ),
    ]
