# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_option_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='visted',
            new_name='visited',
        ),
    ]
