# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0005_auto_20171219_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votelog',
            name='voter',
        ),
        migrations.AddField(
            model_name='votelog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
