# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20171220_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='option',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=10240),
        ),
    ]
