# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20171221_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='option',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10240),
        ),
    ]
