# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20171221_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image_url',
            field=models.ImageField(upload_to=b''),
        ),
    ]
