# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20171221_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='visited',
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
