# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_game_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='vote_cicle_hour',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='option',
            name='image_url',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
