# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_auto_20171222_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='option',
            name='image_url',
            field=models.ImageField(default=None, null=True, upload_to=b''),
        ),
    ]
