# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20171222_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duplicate_vote',
            field=models.BooleanField(default=False),
        ),
    ]
